### ISSUE TITLE
schema呼起app并打开目标页面

### ISSUE THREAD

**Issue by xiong199208** [JZ-Darkal/AndroidHttpCapture#10]
最近碰到一个需求，微信的一个黑科技，//multiwebview命令，可以将微信主程序和微信的公众号打开的webview分离成两个任务栈，后台可以切换。但通过微信的包名隐式跳转，就只能跳转到微信的主程序，能不能通过schema直接跳转到微信的webview那个任务栈呢？应该怎么操作？

**Comment by darkal** [comment]
哈哈，我也不确定，我认为除非微信提供专门的webview schema，不然无法实现直接跳转到微信的webview任务栈

**Comment by 772132172** [comment]
小米手机也实现了，感觉它只是后台做了切换吧。

**Comment by xiong199208** [comment]
这样的切换只有系统才能做吗,我打印进程名,两个都是一样的

**Comment by darkal** [comment]
以前可以用 weixin://dl/businessWebview/ 但是现在已经失效了
