### ISSUE TITLE
为什么有些APP抓不到数据？

### ISSUE THREAD

**Issue by cuyoo** [JZ-Darkal/AndroidHttpCapture#11]
oschina的android客户端V2.8.1
设置了代理，但接口数据基本都抓不到，只能拿到普通的图片文件。
别的APP，比如打开京东的APP，就能拿到http和https的数据。
有什么办法？

**Comment by darkal** [comment]
刚看了一下，oschina客户端用的是 [loopj/android-async-http](https://github.com/loopj/android-async-http) 网络请求库 ，这个库的当前版本不能读取系统的代理设置，解决方法参考这里 https://github.com/loopj/android-async-http/issues/1070
