### ISSUE TITLE
预览请求列表中，有的item能够点击查看数据详情，但是也有挺多不能点击进入数据详情

### ISSUE THREAD

**Issue by 569785819** [JZ-Darkal/AndroidHttpCapture#2]
预览请求列表中，有的item能够点击查看数据详情，但是也有挺多不能点击进入数据详情
而且我导出的har到网页上分析，提示json异常

**Comment by darkal** [comment]
数据详情指的是Response Content的内容吗？--》 当初就是这样设计的，只有返回包的contentType
`contentType.startsWith("text/") ||
                contentType.startsWith("application/x-javascript") ||
                contentType.startsWith("application/javascript")  ||
                contentType.startsWith("application/json")  ||
                contentType.startsWith("application/xml")  ||
                contentType.startsWith("application/xhtml+xml")
                )`（ BrowserMobHttpUtil.java:125）满足这些的才会保存Response Content

**Comment by darkal** [comment]
@569785819 麻烦发一下har文件，我看下是什么问题 ( ̀⌄ ́)

**Comment by darkal** [comment]
如果是无法进去这个activity的话麻烦反馈下手机型号还有系统版本
![image](https://www.darkal.cn/imgd.php?src=/2016/09/230686663947787928.jpg&width=350)<br>

**Comment by cwjfeifei** [comment]
@darkal 在public void addItem(String title, final String value)方法里面加多
 if (TextUtils.isEmpty(value)) {
            valueTextView.setText("");
        } else {
            valueTextView.setText(value.substring(0, value.length() > 50 ? 50 : value.length()));
        }
这个判断就可以了，这样就可以跳转了

**Comment by darkal** [comment]
@cwjfeifei 感谢感谢，已经合并至master
