### ISSUE TITLE
what is "cn.darkal.networkdiagnosis.BR" 

### ISSUE THREAD

**Issue by jiashie** [JZ-Darkal/AndroidHttpCapture#22]
compile error: cannot resolve symbol "cn.darkal.networkdiagnosis.BR" in cn.darkal.networkdiagnosis.Adapter.ContentFilterAdapter and cn.darkal.networkdiagnosis.Adapter.PageFilterAdapter.

Is there some file missing?

**Comment by darkal** [comment]
It is a problem caused by android-apt plugin. It ignores the provided dependency that data binding plugin adds.
Adding: com.neenbedankt.gradle.plugins:android-apt:1.8 to your gradle file.Try file-> Invalidate Caches/Restart, then rebuild the project.
