### ISSUE TITLE
能按照app来分类这些请求数据吗

### ISSUE THREAD

**Issue by vivian2011** [JZ-Darkal/AndroidHttpCapture#24]
希望能按照uid来分类抓到的这些请求，请问可行吗？

**Comment by darkal** [comment]
不通过vpn service来抓取的请求都无法识别来自哪个app，目前版本是通过http proxy的方式抓包的，请求中不包含app信息。

**Comment by vivian2011** [comment]
@darkal   不好意思回复晚了，非常感谢～
