### ISSUE TITLE
按照issue中的方法去做了，还是在编译时出现问题：找不到符号：BR

### ISSUE THREAD

**Issue by MrTaoGe** [JZ-Darkal/AndroidHttpCapture#26]
在用android studio2.3.3编译这个项目的时候会遇到类似下面这个编译问题：
Error:(13, 34) 错误: 找不到符号
符号:   类 BR
位置: 程序包 cn.darkal.networkdiagnosis
在app的build.gradle文件中添加了compile 'com.neenbedankt.gradle.plugins:android-apt:1.8'，然后执行file->Invalidate Caches/Restart以后这个问题没有得到解决，不知道是不是还有哪里配置不对。

**Comment by darkal** [comment]
部署了travis CI持续集成，项目参数是没有问题的，对照看下gradle buildtools的版本是不是和我提交的一致？  https://travis-ci.org/JZ-Darkal/AndroidHttpCapture/builds/273218761

**Comment by MrTaoGe** [comment]
编译通过了，可以运行了[/赞]。发现我的gradle是2.3.3版本，当前项目中的版本是2.2.2，改成2.2.2以后就OK了。对gradle这块不是很熟悉，想请教一下，为什么高版本的gradle会编译失败，不兼容不低版本吗？不知道作者是通过什么途径对gradle进行详细的学习了解的，想深入学习一下。[/抱拳]

**Comment by darkal** [comment]
高版本的gradle应该也是没问题的，但是没有测试过。。我对于gradle也是仅仅会用，没有刻意的去学习哈哈
