### ISSUE TITLE
transaction.commitNow() no find the method

### ISSUE THREAD

**Issue by ChangSpring** [JZ-Darkal/AndroidHttpCapture#3]
我把app.gradle 文件中所有的com.android.support:修改为23版本的,找不到这个方法了 commitNow()这个方法只有在24中有吗  还是怎么回事?

**Comment by darkal** [comment]
项目是基于sdk 24来进行开发的，如果改为23的话会有一些24新增的方法找不到，建议还是使用sdk 24来进行编译
