### ISSUE TITLE
Proxy or Vpn

### ISSUE THREAD

**Issue by chenenyu** [JZ-Darkal/AndroidHttpCapture#4]
这个项目现在是使用代理实现的，对于使用`VpnService`实现的话，不知道作者有没有什么好的想法呢？

**Comment by darkal** [comment]
使用VpnService的优势在于可以抓取除了http以外的请求，也可以判断流量具体来自哪个应用。下一个版本计划用VpnService+HTTP代理的方式来实现。

**Comment by chenenyu** [comment]
原来尝试过类似的抓包，后来因为某些原因放弃了，我会持续关注，希望作者快快更新 ：）
