### ISSUE TITLE
packet capture 有一个可以只捕获一个应用的全部流量的方法，很赞

### ISSUE THREAD

**Issue by fbigun** [JZ-Darkal/AndroidHttpCapture#40]
希望可以新增功能，看packet capture文档说是利用vpn实现。

**Comment by fbigun** [comment]
不用设置应用的代理相关。不用管应用支不支持代理等。

**Comment by darkal** [comment]
嗯，是的，用vpn service可以全局转发，我抽空把这个项目换成VPN service的实现

**Comment by qkmaosjtu** [comment]
harlog里不包含app的特征吗？如果能有一个特征去区分App就好了
