### ISSUE TITLE
请问怎样通过browermob-proxy拦截HTTPS请求的？

### ISSUE THREAD

**Issue by RSencoder** [JZ-Darkal/AndroidHttpCapture#45]
我目前看了browermob的MITM中间人的说明，里面很多证书操作不太明白。请问怎样通过browermob拦截HTTPS请求，需要怎么安装证书，用到哪些api？

**Comment by darkal** [comment]
ProxyUtils 会对https的请求设置http代理，将请求转发至browermob所监听的端口（8888）上，然后需要安装一下自签名的ca证书，不然浏览器会拒绝链接。安装证书的话可以在app设置中安装，也用文件管理器 手动安装 sdcard://har/littleproxy-mitm.pem
