### ISSUE TITLE
寻找失踪人口 :)

### ISSUE THREAD

**Issue by hexin46373** [JZ-Darkal/AndroidHttpCapture#48]
看动态作者失踪好几个月了,翻看了历往的Issues,作者说抽空了用vpnservice来实现,坐等作者的成品。

希望作者没有被卖到大山里去啊,卖到大山里去了你吱一声,我好来救你。

@darkal

**Comment by Ray-Eldath** [comment]
同问啊... 多好的项目千万别弃坑了... @darkal

**Comment by darkal** [comment]
@hexin46373 @Ray-Eldath  没有弃坑呢，前段时间618太忙了，大促后会重新开始弄的，感谢大家的支持！

**Comment by hexin46373** [comment]
哈哈,那就好啊,@darkal加油,我等小白就只能站在你的肩膀上傲世天下。

**Comment by hexin46373** [comment]
对了,目前git上有另外一个项目,https部分还未开源,说是要1000star后才开源https部分。
你们可以相互交流下啊,下面是链接
简书:https://www.jianshu.com/p/ae4d433597ce
Github: https://github.com/huolizhuminh/NetWorkPacketCapture
APP下载地址：https://www.pgyer.com/REhj

**Comment by darkal** [comment]
@hexin46373 嗯，思路大致一样，不用的地方就是现有APP其实是截取HTTP请求的，VpnService收到的是socket请求包，需要实现socket流量转为http协议进行抓包改包，之后再封装成socket请求包返回给VpnService

**Comment by hexin46373** [comment]
@darkal 另外有个firewall是基于vpn做的一个项目,不过没有做https, https://github.com/zheying/Firewall

**Comment by darkal** [comment]
@gy8958398 已经修复了

**Comment by gy8958398** [comment]
感谢 @darkal
