### ISSUE TITLE
https的抓不了啊

### ISSUE THREAD

**Issue by onlylikews** [JZ-Darkal/AndroidHttpCapture#5]
我尝试抓https的，提示502呀，没法忽略证书或者伪造证书吗？

**Comment by darkal** [comment]
应用第一次启动的时候会弹窗安装一个证书，安装后可以尝试访问https://www.baidu.com ，可以访问的话说明https抓包功能没问题，如果在安装的情况下还是无法抓取某些应用的https请求的话，说明该应用为了防止进行中间人攻击做了证书校验，这样的话就无法抓取了
