### ISSUE TITLE
har文件保存失败

### ISSUE THREAD

**Issue by yoni803** [JZ-Darkal/AndroidHttpCapture#57]
分享的时候提示har文件保存失败，上传也看不到验证码

**Comment by 00364291** [comment]
相同问题，有些机器har保存失败。
另外上传是上传到哪里，能否自定义配置呢

**Comment by darkal** [comment]
目前上传地址没有配置，需要在代码中MainActivity自行填写

**Comment by darkal** [comment]
har保存失败的话检查一下是否给了读写存储权限

**Comment by yoni803** [comment]
权限都有的，还是保存不了，我在虚拟机上试过也不行

**Comment by darkal** [comment]
@yoni803 我这里用三星7.0测试保存文件没有问题，具体保存不了的机器是什么型号，android版本多少呢？

**Comment by yoni803** [comment]
魅蓝x安卓6的底包，虚拟机上是安卓5的底包

**Comment by yoni803** [comment]
可以了，谢谢
