### ISSUE TITLE
BP 为毛一直不能用啊。隔段时间就出问题

### ISSUE THREAD

**Issue by hhhaiai** [JZ-Darkal/AndroidHttpCapture#65]
cn.darkal.networkdiagnosis.BR

这个是怎么生成的？

**Comment by hhhaiai** [comment]
编写 。代码提示直接出了，编译 死活运行不了。

**Comment by darkal** [comment]
https://travis-ci.org/JZ-Darkal/AndroidHttpCapture 自动化编译都弄好了，先从自己的环境找下原因吧

**Comment by hhhaiai** [comment]
> https://travis-ci.org/JZ-Darkal/AndroidHttpCapture 自动化编译都弄好了，先从自己的环境找下原因吧
 
是在找原因。主要是因为什么依赖的问题

**Comment by hhhaiai** [comment]
我发起个 PR吧

**Comment by hhhaiai** [comment]
gradle 里wrapper多的导致部分场景下 编译异常
