### ISSUE TITLE
tracepath.so

### ISSUE THREAD

**Issue by wgbuaa** [JZ-Darkal/AndroidHttpCapture#7]
请问能否将tracepath.so的jni代码开源，因为jni里面的native代码可能是通过函数名称映射到java层的，在某些机型上会报unsatisfyLinkerError，有个解决方案就是改变jni映射的方式，所以希望作者能开源下so的jni代码。

**Comment by darkal** [comment]
@wgbuaa 这是TraceRoute部分的用到的jni代码 https://github.com/Lede-Inc/LDNetDiagnoService_Android/tree/master/LDNetDiagnoService_Android/jni
