### ISSUE TITLE
可以考虑一下做一个把证书导出然后我们可以拿到电脑上安装的功能

### ISSUE THREAD

**Issue by No5972** [JZ-Darkal/AndroidHttpCapture#73]
注意到可以通过电脑修改daili服务器到设置实现手机抓电脑数据包，因为电脑硬盘没有空间，所以希望通过手机来拦截数据包。但是发现APP缺少一个导出证书的功能。如果能**导出证书**我们就可以拿到电脑上安装，这样就能对电脑的HTTPS请求进行获取了。

**Comment by chengs2035** [comment]
在手机的主目录下有个har文件夹，里面是证书
