### ISSUE TITLE
代码有误

### ISSUE THREAD

**Issue by cwjfeifei** [JZ-Darkal/AndroidHttpCapture#8]
for (HarNameValuePair pair : harRequest.getHeaders()) {
            if (pair.getName().equals("Cookie")) {
                break;
            }
            Log.e("Request Header",pair.getName());
            addItem(pair.getName(), pair.getDecodeValue());
        }
这里的不应该break，不然请求头信息很多拿不到

**Comment by darkal** [comment]
@cwjfeifei 是的，这里不应该break，已修改，感谢
