### ISSUE TITLE
har/littleproxy-mitm.pem文件在哪？

### ISSUE THREAD

**Issue by oOtroyOo** [JZ-Darkal/AndroidHttpCapture#81]
说明文档说了需要安装证书。App内给了提示，没有安装。
经过源码查找。需要一个har/littleproxy-mitm.pem文件。可是存储目录里找不到，而且暂且也没有找到保存该文件的代码。

**Comment by oOtroyOo** [comment]
似乎明白了。可能是安卓10强制不给存储路径权限。我降api到27就弹出来了

**Comment by darkal** [comment]
嗯，暂时先把api降到27，之后抽空再改，这几年安卓变化真大 -。-

**Comment by ooftf** [comment]
安装证书的密码是什么

**Comment by ooftf** [comment]
我手动安装的，让我输入密码

**Comment by ooftf** [comment]
我知道了，让我输入手机密码，不是证书密码。。。
