### ISSUE TITLE
Android P BC provider 不提供 RSA加密算法，什么时候有空适配一下高版本

### ISSUE THREAD

**Issue by Rob8it** [JZ-Darkal/AndroidHttpCapture#83]
org.bouncycastle.operator.OperatorCreationException: cannot create signer: The BC provider no longer provides an implementation for Signature.SHA512WITHRSA.  Please see https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html for more details.

**Comment by darkal** [comment]
已经解决了

**Comment by menglide** [comment]
MIUI3系统无法安装证书，有空升级下包吧
